name: "Test"
on:
  push:
    branches:
      - master
    paths:
      - "git-app/*/**"
      - ".github/workflows/test-long-pass.yml"
    tags-ignore:
      - v*.*.*
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "git-app/*/**"
      - ".github/workflows/test-long-pass.yml"
jobs:
  git-app-test:
    name: git-app-test
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Shallow clones should be disabled for SonarCloud analysis
      - name: To long pass
        run: |
          echo "Workflow started"
          sleep 30 
          echo "Pass resumed after delay"
