name: "Test Long Fail"
on:
  push:
    branches:
      - master
    paths:
      - "git-app/*/**"
      - ".github/workflows/test-long-fail.yml"
    tags-ignore:
      - v*.*.*
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "git-app/*/**"
      - ".github/workflows/test-long-fail.yml"
jobs:
  git-app-test-long-fail:
    name: git-app-test-long-fail
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Shallow clones should be disabled for SonarCloud analysis
      - name: to long fail
        run: |
          echo "Workflow started, to fail in 3 min"
          sleep 60
          echo "Workflow started, to fail in 3 min"
